### ISSUE TITLE
ScalaTestの書き方について

### ISSUE THREAD

**Issue by 3tty0n** [titech-is-cs115/lx03#1]
sbtを利用して開発するとき、Testフォルダ内に*.scalaを作り、そこにデバッグのための様々なテストケースを書く必要があります。
ScalaTestに関するドキュメントはどこにありますか？
教えてくださると助かります。

**Comment by wakita** [comment]
@3tty0n さん、

[ScalaTestのドキュメント全体](http://www.scalatest.org/user_guide)はかなりの分量があるので読破が大変です。ScalaTest のテスト基盤には複数があって、ぼくらはその一部しか使っていないので、その部分をよく読めば大丈夫です。

[Using matchers](http://www.scalatest.org/user_guide/using_matchers) が一番参考になるでしょう。今日、授業で提示したテストケース例にも含まれていた、以下の記法が解説されています。
- should be
- should not be
- should have length
- should include

**Comment by 3tty0n** [comment]
ありがとうございます
個人的に調べてみたところspecs2が使われてたりするそうです
