### ISSUE TITLE
パズルの問題について

### ISSUE THREAD

**Issue by KSato0428** [titech-is-cs115/lx03#2]
パズルの中で
「1が?コ」と書かれていた場合、1は文字の1ですか？それとも数字の1ですか？

例えば前者だった場合、11は1という文字が2個あることになり、後者だった場合は11は数字の1と異なるので1は0個ということになります

**Comment by KSato0428** [comment]
すみません、数字って書いてありましたね

**Comment by wakita** [comment]
:smile:
